package com.indianservers.circuitssimulator.guide

import com.indianservers.circuitssimulator.domain.Kind

/** Offline, structured lesson content. Screens render these definitions rather than encoding lesson logic. */
object LessonCatalog {
    private fun s(id:String,instruction:String,criterion:LessonCriterion,why:String,
                  vararg hints:String,focus:Set<Kind> = emptySet(),pins:List<GuidePin> = emptyList(),
                  choices:List<String> = emptyList())=
        LessonStep(id,instruction,criterion,why,hints.toList(),focus,pins,choices)

    val lessons:List<GuidedLesson> = listOf(
        GuidedLesson("first-led","Light Your First LED","Build a safe LED loop from individual parts.",
            "Getting Started",objectives=listOf("Identify battery polarity","Limit LED current","Close a wired loop"),
            initialCircuit={LessonTemplates.groundOnly("Light Your First LED")},
            allowedKinds=setOf(Kind.BATTERY,Kind.RESISTOR,Kind.LED,Kind.GROUND),
            steps=listOf(
                s("battery","Choose Battery below, then tap the canvas to place it.",
                    LessonCriterion.Count(Kind.BATTERY),"A battery provides the voltage that moves charge around the loop.",
                    "Open the component picker or use the Battery card.","Tap an empty area of the canvas after choosing Battery.",focus=setOf(Kind.BATTERY)),
                s("resistor","Place a resistor.",LessonCriterion.Count(Kind.RESISTOR),
                    "The resistor limits current so the LED is not overdriven.",
                    "Find Resistor in the component tray.","A value around 330 Ω works with the default 9 V battery.",focus=setOf(Kind.RESISTOR)),
                s("led","Place an LED.",LessonCriterion.Count(Kind.LED),
                    "An LED conducts mainly from its anode to its cathode.",
                    "Look for LED in the component tray.","Its + pin is the anode.",focus=setOf(Kind.LED)),
                s("battery_resistor","Wire Battery + to either resistor pin.",
                    LessonCriterion.SourceToResistor(),"The source must feed the current-limiting resistor.",
                    "Tap the battery + pin, then a resistor pin.","Wire direction on the screen does not matter.",
                    pins=listOf(GuidePin(Kind.BATTERY,0))),
                s("resistor_led","Wire the resistor's free pin to LED anode (+).",
                    LessonCriterion.ResistorToLedAnode,"This puts the resistor in the LED's current path.",
                    "The LED anode is pin +.","Use the resistor pin that is not already on Battery +.",
                    pins=listOf(GuidePin(Kind.LED,0))),
                s("led_return","Wire LED cathode (−) to Battery −.",
                    LessonCriterion.LedCathodeToSource(),"Current needs a return path to the source.",
                    "The LED cathode is pin −.","Connect that pin to the battery's negative terminal.",
                    pins=listOf(GuidePin(Kind.LED,1),GuidePin(Kind.BATTERY,1))),
                s("reference","Wire Battery − to Ground (0 V reference).",
                    LessonCriterion.SourceGrounded(),"Ground sets the reference for all measured voltages.",
                    "A Ground symbol is already on the canvas.","A wire can join a pin that already has another wire.",
                    pins=listOf(GuidePin(Kind.BATTERY,1),GuidePin(Kind.GROUND,0))),
                s("topology","Check that the resistor really is in series with the LED.",
                    LessonCriterion.LedSeries(),"A direct bypass around the resistor can cause too much LED current.",
                    "Follow the path from Battery + through Resistor and LED to Battery −.",
                    "Move a wire if it joins the wrong resistor pin.",focus=setOf(Kind.RESISTOR,Kind.LED)),
                s("run","Start the simulation using the Run control.",LessonCriterion.RunStarted(),
                    "Simulation calculates currents and voltages from your actual circuit.",
                    "Open Simulation and choose Run.",focus=setOf(Kind.LED)),
                s("observe","Observe the lit LED and its calculated current.",
                    LessonCriterion.WorkingLed(),"LED brightness follows forward current, not merely the presence of a battery.",
                    "If it stays dark, inspect the LED polarity and every wire.",
                    "A 330 Ω resistor should keep current in a useful range.")),
            completionNote="You built a closed circuit with a current-limiting resistor. The LED lit because forward current flowed through it."),

        GuidedLesson("switch-led","Control an LED with a Switch","Open and close a real current path.",
            "Getting Started",objectives=listOf("Build a series loop","Compare open and closed switches"),
            initialCircuit={LessonTemplates.groundOnly("Control an LED with a Switch")},
            allowedKinds=setOf(Kind.BATTERY,Kind.SWITCH,Kind.RESISTOR,Kind.LED,Kind.GROUND),
            steps=listOf(
                s("battery","Place a battery.",LessonCriterion.Count(Kind.BATTERY),"The battery powers the loop.","Choose Battery in the tray."),
                s("switch","Place a switch.",LessonCriterion.Count(Kind.SWITCH),"The switch can break or complete the path.","Choose Switch in the tray."),
                s("resistor","Place a resistor.",LessonCriterion.Count(Kind.RESISTOR),"This limits LED current.","Use the default 330 Ω."),
                s("led","Place an LED.",LessonCriterion.Count(Kind.LED),"Its anode must face the positive path.","Find the + pin."),
                s("source_switch","Wire Battery + to a switch pin.",LessonCriterion.Link(Kind.BATTERY,Kind.SWITCH,0),
                    "Power should pass through the switch.","Tap Battery +, then either switch pin."),
                s("switch_resistor","Wire the other switch pin to the resistor.",LessonCriterion.Link(Kind.SWITCH,Kind.RESISTOR),
                    "This keeps the switch in series.","Use the switch pin still free."),
                s("resistor_led","Wire the resistor to LED anode (+).",LessonCriterion.ResistorToLedAnode,
                    "The resistor protects the LED.","The LED + pin is its anode."),
                s("return","Wire LED cathode (−) to Battery −.",LessonCriterion.LedCathodeToSource(),
                    "The loop needs a return path.","Use the LED − pin."),
                s("ground","Wire Battery − to Ground.",LessonCriterion.SourceGrounded(),
                    "Ground is the 0 V measurement reference.","Ground is already on the canvas."),
                s("loop","Check the switch, resistor and LED form one series loop.",
                    LessonCriterion.LedSeries(withSwitch=true),"Every part must be on the same current path.",
                    "Trace the path from + through Switch, Resistor and LED back to −."),
                s("run","Start simulation.",LessonCriterion.RunStarted(),"Simulation evaluates the switch state.","Use the Run control."),
                s("off","Tap the switch to open it.",LessonCriterion.SwitchToggled(false),
                    "An open switch interrupts current.","Tap the switch body on the canvas."),
                s("dark","Observe the LED go dark.",LessonCriterion.LedOff(),
                    "With the path open, almost no current can flow.","Inspect the LED current reading."),
                s("on","Tap the switch to close it.",LessonCriterion.SwitchToggled(true),
                    "Closing the contact completes the loop.","Tap the switch again."),
                s("bright","Observe the LED lighting again.",LessonCriterion.WorkingLed(),
                    "The completed path restores forward current.","Check current and polarity.")),
            completionNote="Opening the switch stopped current. Closing it restored the LED current and light."),

        GuidedLesson("measure-voltage","Measure Voltage with a Multimeter","Place probes across three parts.",
            "Measuring Circuits",objectives=listOf("Select DC voltage","Measure across a component"),
            initialCircuit={LessonTemplates.led("Voltage measurements")},
            steps=listOf(
                s("run","Start the LED circuit.",LessonCriterion.RunStarted(),"Readings need an operating circuit.","Use Run in the Simulation control."),
                s("battery","Set the meter to DC V and attach V+ to Battery +, COM to Battery −.",
                    LessonCriterion.ProbeVoltage(Kind.BATTERY,min=8.0,max=10.0),
                    "Voltage is measured between two nodes; the meter goes across the part.",
                    "Open the multimeter from Simulation.","Tap a wire, then V+ or COM, for each probe."),
                s("resistor","Measure voltage across the resistor.",
                    LessonCriterion.ProbeVoltage(Kind.RESISTOR,min=5.0,max=8.0),
                    "The resistor drops most of the battery voltage in this loop.",
                    "Move V+ to the resistor's input node and COM to its output node."),
                s("led","Measure voltage across the LED.",
                    LessonCriterion.ProbeVoltage(Kind.LED,min=1.0,max=3.5),
                    "A forward-biased LED has a characteristic voltage drop.",
                    "Place V+ at LED anode and COM at cathode.")),
            completionNote="You measured voltage in parallel across the battery, resistor and LED. The drops add to the source voltage."),

        GuidedLesson("measure-current","Measure Current","Insert the virtual ammeter in a branch.",
            "Measuring Circuits",objectives=listOf("Distinguish current from voltage measurement","Measure series current"),
            initialCircuit={LessonTemplates.led("Current measurement")},
            steps=listOf(
                s("run","Start the LED circuit.",LessonCriterion.RunStarted(),"Current exists only when the circuit is powered and closed.","Use Run."),
                s("current","Open Multimeter, select a resistor branch wire, then tap A.",
                    LessonCriterion.ProbeCurrent(.005,.03),
                    "An ammeter is inserted in series. Its low resistance makes direct connection across a source unsafe.",
                    "Tap a wire touching the resistor.","Choose A on the selected wire, then inspect the live current.")),
            completionNote="The meter inserted itself into a series branch and measured the actual solver current."),

        GuidedLesson("ohms-law","Explore Ohm's Law","Change voltage and resistance, then measure current.",
            "Electrical Basics",objectives=listOf("Explore V = I × R","Observe how resistance changes current"),
            initialCircuit=LessonTemplates::ohm,
            steps=listOf(
                s("voltage","Select the source and set it near 5 V.",
                    LessonCriterion.PropertyRange(Kind.SOURCE,"voltage",4.8,5.2),
                    "Voltage is the electrical potential difference driving current.","Tap the source to edit Voltage."),
                s("resistance","Set the resistor near 1 kΩ.",
                    LessonCriterion.PropertyRange(Kind.RESISTOR,"resistance",950.0,1050.0),
                    "Resistance opposes current flow.","Tap the resistor and enter 1 kΩ."),
                s("run","Start simulation.",LessonCriterion.RunStarted(),"The solver calculates current from voltage and resistance.","Use Run."),
                s("first_current","Measure the resistor branch current with the multimeter.",
                    LessonCriterion.ProbeCurrent(.004,.006),"At about 5 V and 1 kΩ, current should be near 5 mA.",
                    "Tap a resistor wire, then A."),
                s("double_resistance","Increase the resistor near 2 kΩ.",
                    LessonCriterion.PropertyRange(Kind.RESISTOR,"resistance",1900.0,2100.0),
                    "Doubling resistance approximately halves current when voltage stays fixed.",
                    "Edit the same resistor; current is calculated, never entered directly."),
                s("second_current","Measure current again and compare it with the first reading.",
                    LessonCriterion.ProbeCurrent(.002,.003),"The same 5 V now drives roughly half the current.",
                    "Keep the multimeter in current mode on a resistor branch.")),
            completionNote="At fixed voltage, greater resistance reduced the simulated current. Your readings illustrate V = I × R."),

        GuidedLesson("series-resistors","Resistors in Series","Build a single path and compare voltage drops.",
            "Electrical Basics",objectives=listOf("Build a series branch","Measure two voltage drops"),
            initialCircuit={LessonTemplates.resistorStart("Resistors in Series")},
            allowedKinds=setOf(Kind.RESISTOR,Kind.SOURCE,Kind.GROUND),
            steps=listOf(
                s("first","Place the first resistor.",LessonCriterion.Count(Kind.RESISTOR,1),
                    "Each resistor will take part of the source voltage.","Choose Resistor."),
                s("second","Place a second resistor.",LessonCriterion.Count(Kind.RESISTOR,2),
                    "Series parts share one current path.","Choose Resistor again."),
                s("wire","Wire Source + → resistor → resistor → Source −.",
                    LessonCriterion.SeriesResistors,"The two resistances add in a single branch.",
                    "Join the middle resistor pins together.","Use the remaining ends at Source + and Source −."),
                s("run","Start simulation.",LessonCriterion.RunStarted(),"The solver divides the source voltage across the two resistors.","Use Run."),
                s("first_drop","Measure voltage across the first resistor.",
                    LessonCriterion.ProbeVoltage(Kind.RESISTOR,0,3.0,7.0),
                    "Equal resistors should have similar drops.","Use DC V probes at opposite ends of R1."),
                s("second_drop","Measure voltage across the second resistor.",
                    LessonCriterion.ProbeVoltage(Kind.RESISTOR,1,3.0,7.0),
                    "The individual drops add to approximately 10 V.","Move both probes to R2.")),
            completionNote="Two equal series resistors shared the 10 V source. Their branch current was the same."),

        GuidedLesson("parallel-resistors","Resistors in Parallel","Create two branches and compare their voltages.",
            "Electrical Basics",objectives=listOf("Build two current paths","Observe equal branch voltage"),
            initialCircuit={LessonTemplates.resistorStart("Resistors in Parallel")},
            allowedKinds=setOf(Kind.RESISTOR,Kind.SOURCE,Kind.GROUND),
            steps=listOf(
                s("first","Place one resistor.",LessonCriterion.Count(Kind.RESISTOR,1),
                    "Each branch will connect across the source.","Choose Resistor."),
                s("second","Place a second resistor.",LessonCriterion.Count(Kind.RESISTOR,2),
                    "This creates another path for current.","Choose Resistor again."),
                s("wire","Wire both resistors across Source + and Source −.",
                    LessonCriterion.ParallelResistors,"Parallel parts share the same two electrical nodes.",
                    "Connect one end of each resistor to +.","Connect their other ends to −."),
                s("run","Start simulation.",LessonCriterion.RunStarted(),"The solver finds each branch current and voltage.","Use Run."),
                s("first_voltage","Measure the voltage across the first branch.",
                    LessonCriterion.ProbeVoltage(Kind.RESISTOR,0,9.0,11.0),
                    "A parallel branch sees nearly the full source voltage.","Use DC V probes on R1."),
                s("second_voltage","Measure the voltage across the other branch.",
                    LessonCriterion.ProbeVoltage(Kind.RESISTOR,1,9.0,11.0),
                    "Both branches share the same voltage even though current splits.","Move probes to R2.")),
            completionNote="The parallel resistors shared source voltage and provided multiple current paths."),

        GuidedLesson("led-polarity","Why Isn't the LED Lighting?","Diagnose a powered but dark LED.",
            "Troubleshooting",objectives=listOf("Identify LED polarity","Repair a reversed connection"),
            initialCircuit={LessonTemplates.led("LED polarity fault","reversed_led")},
            steps=listOf(
                s("observe","Start simulation and inspect the dark LED.",LessonCriterion.RunStarted(),
                    "A powered circuit can still fail if a polarized device faces the wrong way.","Use Run."),
                s("diagnose","What is the most likely problem?",
                    LessonCriterion.Answer("LED polarity"),"An LED has distinct anode and cathode terminals.",
                    "Check whether current has a complete path.","LEDs conduct mainly in one direction.",
                    "Look at the + and − labels beside the LED.",
                    choices=listOf("LED polarity","Battery has no voltage","Resistor is missing")),
                s("repair","Disconnect and reconnect the LED so current enters its anode (+).",
                    LessonCriterion.WorkingLed(),"Forward current must enter the anode and leave the cathode.",
                    "Remove the two LED wires and reconnect them to opposite pins.",
                    "Resistor output should reach LED +; LED − should reach Battery −.",
                    pins=listOf(GuidePin(Kind.LED,0),GuidePin(Kind.LED,1)))),
            completionNote="You diagnosed a reversed LED and restored forward current by correcting its two connections."),

        GuidedLesson("short-circuit","Find the Short Circuit","Locate and remove a wire bypassing the load.",
            "Troubleshooting",objectives=listOf("Recognize a source short","Repair the bypass"),
            initialCircuit={LessonTemplates.led("Short circuit fault","short")},
            steps=listOf(
                s("observe","Inspect the circuit's short-circuit warning.",
                    LessonCriterion.IssuePresent("SOURCE_SHORT"),
                    "A direct path between source terminals bypasses the load and can cause excessive current.",
                    "Open Diagnostics to find the source warning."),
                s("diagnose","Which connection causes the fault?",
                    LessonCriterion.Answer("Bypass wire"),"The direct + to − connection avoids the resistor and LED.",
                    "Follow all wires leaving Battery +.","Look for a path straight back to Battery −.",
                    choices=listOf("Bypass wire","LED body","Ground symbol")),
                s("repair","Delete the direct + to − bypass wire, leaving the resistor and LED path.",
                    LessonCriterion.IssueAbsent("SOURCE_SHORT"),
                    "Removing the bypass allows current through the intended load.",
                    "Tap the wire that joins Battery + to Battery −, then Delete."),
                s("verify","Start simulation and verify useful LED current.",
                    LessonCriterion.WorkingLed(),"A repair is confirmed by the actual solved circuit state.",
                    "Use Run if paused.","The LED should light through the resistor.")),
            completionNote="You removed the bypass wire. Current now flows through the load instead of shorting the source."),

        GuidedLesson("open-circuit","Find the Broken Connection","Repair a missing wire in an LED loop.",
            "Troubleshooting",objectives=listOf("Recognize an open path","Restore continuity"),
            initialCircuit={LessonTemplates.led("Open circuit fault","open")},
            steps=listOf(
                s("inspect","Inspect the missing connection between the resistor and LED.",
                    LessonCriterion.IssuePresent("UNWIRED_PIN"),
                    "A missing wire prevents current from completing the loop.",
                    "Use Diagnostics or inspect unconnected pins."),
                s("diagnose","Why is the LED dark?",
                    LessonCriterion.Answer("Open path"),"Current cannot cross an unwired gap.",
                    "Follow the wire path from Battery +.","Find where the path stops.",
                    choices=listOf("Open path","Too much source voltage","Parallel branches")),
                s("repair","Wire the free resistor pin to LED anode (+), then run the circuit.",
                    LessonCriterion.WorkingLed(),"Closing the loop restores forward current.",
                    "Connect the resistor's unconnected end to the LED + pin.",
                    pins=listOf(GuidePin(Kind.RESISTOR,1),GuidePin(Kind.LED,0)))),
            completionNote="You found a gap, connected the missing wire, and verified current through the LED.")
    )

    val byId=lessons.associateBy { it.id }
}
